import { Card, CardContent } from "@/components/ui/card"
import Link from "next/link"

export default function TroubleshootingPage() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold mb-4 text-white">Troubleshooting</h1>
        <p className="text-gray-400 mb-6">
          Solutions for common issues you might encounter when using Fardo Encryption.
        </p>
      </div>

      <Card className="bg-gray-950 border-gray-800">
        <CardContent className="p-6">
          <div className="prose prose-invert max-w-none">
            <h2>Common Issues and Solutions</h2>

            <h3>Encryption and Decryption Issues</h3>

            <h4>Error: "Decryption failed. The key may be incorrect."</h4>
            <p>This error occurs when the decryption process fails, usually due to an incorrect key.</p>
            <p>
              <strong>Solutions:</strong>
            </p>
            <ul>
              <li>Double-check that you're using the exact same key that was used for encryption</li>
              <li>Ensure you're using the same encryption algorithm that was used for encryption</li>
              <li>Make sure the encrypted text hasn't been modified or corrupted</li>
              <li>Try copying and pasting the key again to avoid typos</li>
            </ul>

            <h4>Browser Freezes During Encryption/Decryption</h4>
            <p>This can happen when processing large files or complex text.</p>
            <p>
              <strong>Solutions:</strong>
            </p>
            <ul>
              <li>Try using a smaller file (under 100MB)</li>
              <li>Close other browser tabs and applications to free up memory</li>
              <li>Try using a different browser</li>
              <li>For large files, consider splitting them into smaller chunks before encryption</li>
            </ul>

            <h4>Generated Keys Not Working</h4>
            <p>If keys generated by the application don't work for decryption.</p>
            <p>
              <strong>Solutions:</strong>
            </p>
            <ul>
              <li>Make sure you're copying the entire key without missing any characters</li>
              <li>Check if your browser or password manager is modifying the key when you paste it</li>
              <li>Try generating a new key and re-encrypting the data</li>
            </ul>

            <h3>Sharing Issues</h3>

            <h4>Error: "Failed to share encrypted text"</h4>
            <p>This error occurs when there's a problem saving the encrypted text to the server.</p>
            <p>
              <strong>Solutions:</strong>
            </p>
            <ul>
              <li>Check your internet connection</li>
              <li>Try again after a few minutes</li>
              <li>If the encrypted text is very large, try encrypting a smaller portion</li>
              <li>Clear your browser cache and try again</li>
            </ul>

            <h4>Error: "Snippet not found or expired"</h4>
            <p>This error occurs when trying to access a shared snippet that doesn't exist or has expired.</p>
            <p>
              <strong>Solutions:</strong>
            </p>
            <ul>
              <li>Check that you're using the correct URL</li>
              <li>Shared snippets expire after 7 days - the snippet may have been deleted</li>
              <li>Ask the sender to share the content again</li>
            </ul>

            <h3>File Encryption Issues</h3>

            <h4>Encrypted File is Larger Than Expected</h4>
            <p>Encrypted files are typically larger than the original files due to the encryption overhead.</p>
            <p>
              <strong>Solutions:</strong>
            </p>
            <ul>
              <li>
                This is normal behavior - encrypted files include additional data like the initialization vector (IV)
              </li>
              <li>If the file is significantly larger (more than 10%), try compressing the file before encryption</li>
            </ul>

            <h4>Decrypted File Won't Open</h4>
            <p>If a decrypted file can't be opened or appears corrupted.</p>
            <p>
              <strong>Solutions:</strong>
            </p>
            <ul>
              <li>Make sure you used the correct encryption key</li>
              <li>Ensure you're using the same encryption algorithm that was used for encryption</li>
              <li>Check if the original encrypted file was modified or corrupted</li>
              <li>Try decrypting the file again</li>
            </ul>

            <h3>Browser Compatibility Issues</h3>

            <h4>Features Not Working in Older Browsers</h4>
            <p>Fardo Encryption requires modern browser features like the Web Cryptography API.</p>
            <p>
              <strong>Solutions:</strong>
            </p>
            <ul>
              <li>Update your browser to the latest version</li>
              <li>Try using a different modern browser (Chrome, Firefox, Safari, Edge)</li>
              <li>If you must use an older browser, consider using a different encryption tool</li>
            </ul>

            <h3>Logo Settings Issues</h3>

            <h4>Logo Settings Not Saving</h4>
            <p>If your logo customization settings aren't being saved.</p>
            <p>
              <strong>Solutions:</strong>
            </p>
            <ul>
              <li>Check your internet connection</li>
              <li>Make sure all required fields are filled out</li>
              <li>If using a custom logo image, ensure it's a valid image file and not too large</li>
              <li>Clear your browser cache and try again</li>
            </ul>

            <h4>Custom Logo Not Displaying</h4>
            <p>If your custom logo isn't showing up after saving.</p>
            <p>
              <strong>Solutions:</strong>
            </p>
            <ul>
              <li>Refresh the page</li>
              <li>Check if the image URL is accessible</li>
              <li>If using a data URI, make sure it's properly formatted</li>
              <li>Try uploading a different image</li>
            </ul>

            <h3>General Troubleshooting Steps</h3>

            <h4>Clear Browser Cache</h4>
            <p>Clearing your browser cache can resolve many issues:</p>
            <ol>
              <li>Open your browser settings</li>
              <li>Find the option to clear browsing data</li>
              <li>Select cache and cookies</li>
              <li>Clear the data</li>
              <li>Refresh the Fardo Encryption page</li>
            </ol>

            <h4>Try a Different Browser</h4>
            <p>If you're experiencing issues in one browser, try using a different modern browser:</p>
            <ul>
              <li>Google Chrome</li>
              <li>Mozilla Firefox</li>
              <li>Microsoft Edge</li>
              <li>Safari (on macOS)</li>
            </ul>

            <h4>Check for Browser Extensions</h4>
            <p>Some browser extensions can interfere with web applications:</p>
            <ol>
              <li>Try disabling browser extensions, especially ad blockers or privacy tools</li>
              <li>Try using private/incognito mode, which disables most extensions</li>
            </ol>

            <h3>Reporting Issues</h3>
            <p>If you've tried the solutions above and are still experiencing issues:</p>
            <ol>
              <li>
                Check the{" "}
                <Link href="/docs/faq" className="text-primary hover:underline">
                  FAQ
                </Link>{" "}
                to see if your issue is addressed there
              </li>
              <li>
                Report the issue on our{" "}
                <a
                  href="https://github.com/advexon/advexon-encryption/issues"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary hover:underline"
                >
                  GitHub Issues page
                </a>
              </li>
              <li>Include detailed information about the issue, your browser, and steps to reproduce</li>
            </ol>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
